name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            asset_name: ${{ github.event.repository.name }}-amd64
          - target: aarch64-unknown-linux-musl
            asset_name: ${{ github.event.repository.name }}-aarch64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - run: rustup target add ${{ matrix.target }}
      - run: cargo build --release --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.asset_name }}
          path: "${{ github.workspace }}/target/${{ matrix.target }}/release/${{ github.event.repository.name }}"

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: release-*
          path: artifacts
          merge-multiple: true

      - name: Create release
        uses: softprops/action-gh-release@79721680dfc87fb0f44dfe65df68961056d55c38
        with:
          files: artifacts/*
          prerelease: "${{ contains(github.ref_name, 'rc') }}"
          generate_release_notes: true
